// ===== 评估对象类型 =====
const OBJECT_TYPES = [
    { id: 'OT-01', name: '一级供应商', code: 'T1', desc: '直接向主机厂供货的零部件供应商', supplierCount: 4, scenarioRefs: ['Scene-A','Scene-B','Scene-C','Scene-D'] },
    { id: 'OT-02', name: '二级供应商', code: 'T2', desc: '向一级供应商供货的上游供应商', supplierCount: 3, scenarioRefs: ['Scene-A','Scene-B','Scene-H'] },
    { id: 'OT-03', name: '关键原材料供应商', code: 'RM', desc: '钢铁、铝材、锂盐、正极/负极材料等关键原材料供应商', supplierCount: 3, scenarioRefs: ['Scene-E','Scene-F','Scene-L'] },
    { id: 'OT-04', name: '物流服务商', code: 'LG', desc: '干线/支线物流、仓储、国际货代企业', supplierCount: 1, scenarioRefs: ['Scene-M'] },
    { id: 'OT-05', name: '电池全链企业', code: 'BT', desc: '正极/负极/电芯/PACK/BMS 等电池全产业链供应商', supplierCount: 0, scenarioRefs: ['Scene-F'] },
    { id: 'OT-06', name: '出口供应商', code: 'EX', desc: '涉及出口欧盟/北美市场的钢铝电池等CBAM品类供应商', supplierCount: 0, scenarioRefs: ['Scene-G'] },
];

// ===== 行业 =====
const INDUSTRIES = [
    { id: 'IND-01', name: '汽车零部件制造', code: 'AUTO', desc: '包含发动机、底盘、传动、制动等零部件制造', supplierCount: 1 },
    { id: 'IND-02', name: '精密模具制造', code: 'MOLD', desc: '冲压模具、注塑模具、压铸模具等精密模具', supplierCount: 1 },
    { id: 'IND-03', name: '新材料研发', code: 'NMAT', desc: '高分子材料、复合材料、轻量化新材料研发与生产', supplierCount: 1 },
    { id: 'IND-04', name: '动力系统总成', code: 'PWRT', desc: '发动机总成、变速箱总成、电驱动系统', supplierCount: 1 },
    { id: 'IND-05', name: '新能源电池', code: 'BATT', desc: '动力电池电芯、PACK、BMS及储能电池', supplierCount: 1 },
    { id: 'IND-06', name: '底盘零部件', code: 'CHAS', desc: '悬架系统、转向系统、制动系统零部件', supplierCount: 1 },
    { id: 'IND-07', name: '传动系统', code: 'TRAN', desc: '变速器、传动轴、差速器等传动系统零部件', supplierCount: 1 },
    { id: 'IND-08', name: '汽车电子', code: 'ELEC', desc: '车载ECU、传感器、线束、仪表等电子零部件', supplierCount: 1 },
    { id: 'IND-09', name: '锂电正极材料', code: 'CATH', desc: '磷酸铁锂、三元材料等正极材料生产', supplierCount: 1 },
    { id: 'IND-10', name: '钢铁冶炼', code: 'STEL', desc: '碳钢、不锈钢、特种钢冶炼及轧制', supplierCount: 1 },
    { id: 'IND-11', name: '物流运输', code: 'LOGI', desc: '干线/支线运输、仓储、国际货代', supplierCount: 1 },
    { id: 'IND-12', name: '铝材加工', code: 'ALUM', desc: '铝合金铸造、铝型材挤压、铝板轧制', supplierCount: 1 },
];

// ===== 指标类型 (Indicator Categories) =====
const INDICATOR_TYPES = [
    { code: 'A', name: '企业碳管理与绩效', color: '#10B981', desc: '温室气体排放核算、能源结构、碳管理体系、减排绩效、资源循环' },
    { code: 'B', name: '产品低碳与生命周期', color: '#3B82F6', desc: '产品碳足迹、低碳设计、材料工艺、使用阶段贡献、末端管理' },
    { code: 'C', name: '供应链低碳管理', color: '#8B5CF6', desc: '上游供应商碳管理、原材料风险、减排协同、物流低碳化、韧性管理' },
    { code: 'D', name: '合规与信息披露', color: '#F59E0B', desc: '双碳政策符合性、国际贸易碳政策、标准认证、信息透明度' },
    { code: 'E', name: '数字化与数据管理', color: '#06B6D4', desc: '数据采集能力、数据质量、系统自动化、数据安全合规' },
    { code: 'F', name: '低碳技术与战略', color: '#EC4899', desc: '技术创新、新能源布局、碳战略路线图、绿色投融资' },
    { code: 'G', name: '社会责任与行业影响', color: '#14B8A6', desc: '行业领导力、员工关怀、社会公益、环境影响' },
    { code: 'H', name: '市场与客户绿色价值', color: '#F97316', desc: '绿色消费趋势、客户价值感知、营销策略、客户合规反馈' },
];

// ===== 一级指标 (Level-1 Indicators) =====
const LEVEL1_INDICATORS = [
    { code: 'A1', name: '温室气体排放与核算能力', type: 'A' },
    { code: 'A2', name: '能源结构与能源效率', type: 'A' },
    { code: 'A3', name: '碳管理体系与治理能力', type: 'A' },
    { code: 'A4', name: '减排绩效与持续改进', type: 'A' },
    { code: 'A5', name: '资源利用与循环经济', type: 'A' },
    { code: 'B1', name: '产品碳足迹与生命周期评价（LCA）能力', type: 'B' },
    { code: 'B2', name: '产品设计低碳性', type: 'B' },
    { code: 'B3', name: '材料与工艺低碳性', type: 'B' },
    { code: 'B4', name: '产品使用阶段减排贡献', type: 'B' },
    { code: 'B5', name: '产品回收、再利用与末端管理能力', type: 'B' },
    { code: 'C1', name: '上游供应商碳管理与披露', type: 'C' },
    { code: 'C2', name: '关键原材料低碳风险', type: 'C' },
    { code: 'C3', name: '供应链减排协同与赋能', type: 'C' },
    { code: 'C4', name: '物流与运输低碳化', type: 'C' },
    { code: 'C5', name: '供应链韧性与碳风险管理', type: 'C' },
    { code: 'D1', name: '国内双碳政策与行业规范符合性', type: 'D' },
    { code: 'D2', name: '国际贸易与碳边境政策适配', type: 'D' },
    { code: 'D3', name: '标准、认证与第三方核查', type: 'D' },
    { code: 'D4', name: '信息披露与透明度', type: 'D' },
    { code: 'E1', name: '碳与能源数据采集能力', type: 'E' },
    { code: 'E2', name: '数据质量与可追溯性', type: 'E' },
    { code: 'E3', name: '系统化与自动化水平', type: 'E' },
    { code: 'E4', name: '数据安全与合规治理', type: 'E' },
    { code: 'F1', name: '低碳技术与工艺创新', type: 'F' },
    { code: 'F2', name: '新能源与替代方案布局', type: 'F' },
    { code: 'F3', name: '长期碳战略与路线图', type: 'F' },
    { code: 'F4', name: '绿色投融资与激励机制', type: 'F' },
    { code: 'G1', name: '行业领导力与倡导', type: 'G' },
    { code: 'G2', name: '社会责任与员工关怀', type: 'G' },
    { code: 'G3', name: '社会公益与社区贡献', type: 'G' },
    { code: 'G4', name: '环境影响与资源共享', type: 'G' },
    { code: 'H1', name: '市场需求与绿色消费趋势', type: 'H' },
    { code: 'H2', name: '客户绿色价值感知与体验', type: 'H' },
    { code: 'H3', name: '市场推广与营销策略', type: 'H' },
    { code: 'H4', name: '客户绿色要求合规性与反馈机制', type: 'H' },
];

// ===== 二级指标 (Level-2 Indicators) =====
const LEVEL2_INDICATORS = [
    { code: 'A1.1', name: '排放源识别与边界界定', l1: 'A1', desc: '是否系统识别所有排放源并明确核算边界' },
    { code: 'A1.2', name: 'Scope 1 排放核算能力', l1: 'A1', desc: '固定源、移动源等直接排放核算能力' },
    { code: 'A1.3', name: 'Scope 2 排放核算能力', l1: 'A1', desc: '外购电力、热力等间接排放核算能力' },
    { code: 'A1.4', name: 'Scope 3 排放识别与管理', l1: 'A1', desc: '上下游排放识别、数据获取与管理能力' },
    { code: 'A1.5', name: '碳排放核算规范性', l1: 'A1', desc: '核算方法、因子、口径的一致性与规范性' },
    { code: 'A1.6', name: '排放数据核查与审计', l1: 'A1', desc: '是否支持内部或第三方核查' },
    { code: 'A2.1', name: '能源消费结构', l1: 'A2', desc: '化石能源与清洁能源构成情况' },
    { code: 'A2.2', name: '单位产出能耗水平', l1: 'A2', desc: '单位产品或产值能耗表现' },
    { code: 'A2.3', name: '能源计量与监测能力', l1: 'A2', desc: '关键用能节点的计量与监测覆盖' },
    { code: 'A2.4', name: '能效对标与改进', l1: 'A2', desc: '能效对标行业基准及改进措施' },
    { code: 'A2.5', name: '可再生能源使用', l1: 'A2', desc: '绿电、可再生能源采购或自建情况' },
    { code: 'A3.1', name: '碳管理组织与职责', l1: 'A3', desc: '是否设立明确的碳管理组织与职责' },
    { code: 'A3.2', name: '碳管理制度与流程', l1: 'A3', desc: '是否建立制度化管理流程' },
    { code: 'A3.3', name: '内部数据管理与审批', l1: 'A3', desc: '数据采集、审核、确认流程' },
    { code: 'A3.4', name: '碳风险识别与管控', l1: 'A3', desc: '对政策、成本、合规风险的管理' },
    { code: 'A3.5', name: '内部培训与能力建设', l1: 'A3', desc: '员工碳管理能力与培训情况' },
    { code: 'A4.1', name: '历史减排成效', l1: 'A4', desc: '历史排放变化趋势' },
    { code: 'A4.2', name: '减排目标设定', l1: 'A4', desc: '是否设定量化、分阶段目标' },
    { code: 'A4.3', name: '减排项目实施', l1: 'A4', desc: '技术改造、管理优化等措施' },
    { code: 'A4.4', name: '减排绩效评估', l1: 'A4', desc: '对减排效果的评估与复盘' },
    { code: 'A4.5', name: '持续改进机制', l1: 'A4', desc: 'PDCA 或持续改进机制' },
    { code: 'A5.1', name: '原材料利用效率', l1: 'A5', desc: '原材料消耗与损耗控制' },
    { code: 'A5.2', name: '水资源管理', l1: 'A5', desc: '用水效率、回用与节水措施' },
    { code: 'A5.3', name: '废弃物管理与减量', l1: 'A5', desc: '固废、危废管理与减量' },
    { code: 'A5.4', name: '再生资源利用', l1: 'A5', desc: '再生材料或资源回收利用' },
    { code: 'A5.5', name: '循环经济实践', l1: 'A5', desc: '闭环回收、资源循环模式' },
    { code: 'B1.1', name: '产品碳足迹核算能力', l1: 'B1', desc: '是否对产品开展符合标准的碳足迹核算' },
    { code: 'B1.2', name: '生命周期边界定义', l1: 'B1', desc: '是否明确产品生命周期边界与功能单位' },
    { code: 'B1.3', name: '生命周期阶段覆盖', l1: 'B1', desc: '是否覆盖原材料、制造、运输、使用、回收等阶段' },
    { code: 'B1.4', name: '数据来源与质量', l1: 'B1', desc: '一手数据与行业数据库使用情况' },
    { code: 'B1.5', name: '方法学一致性', l1: 'B1', desc: '核算方法、因子选择的一致性与规范性' },
    { code: 'B1.6', name: 'LCA 结果审查与更新', l1: 'B1', desc: '结果评审、更新与版本管理机制' },
    { code: 'B2.1', name: '轻量化设计', l1: 'B2', desc: '通过结构、材料优化降低单位功能质量' },
    { code: 'B2.2', name: '模块化与平台化设计', l1: 'B2', desc: '通过模块化、平台化减少重复开发与排放' },
    { code: 'B2.3', name: '设计阶段碳评估', l1: 'B2', desc: '在设计阶段引入碳影响评估' },
    { code: 'B2.4', name: '可拆解与可回收设计', l1: 'B2', desc: '设计中考虑拆解、回收与再利用' },
    { code: 'B2.5', name: '设计替代方案比较', l1: 'B2', desc: '不同设计方案的碳排放对比分析' },
    { code: 'B3.1', name: '材料碳强度', l1: 'B3', desc: '主要材料单位碳排放水平' },
    { code: 'B3.2', name: '低碳与再生材料使用', l1: 'B3', desc: '再生材料、低碳材料的应用情况' },
    { code: 'B3.3', name: '关键制造工艺碳排放', l1: 'B3', desc: '关键工序能耗与排放水平' },
    { code: 'B3.4', name: '工艺优化与替代', l1: 'B3', desc: '低碳工艺、先进制造技术应用' },
    { code: 'B3.5', name: '工艺稳定性与一致性', l1: 'B3', desc: '工艺排放稳定性与可复制性' },
    { code: 'B4.1', name: '对整车能效的贡献', l1: 'B4', desc: '对整车油耗、电耗或效率的影响' },
    { code: 'B4.2', name: '使用寿命与耐久性', l1: 'B4', desc: '使用寿命延长带来的减排贡献' },
    { code: 'B4.3', name: '使用阶段能耗影响', l1: 'B4', desc: '产品运行过程中能耗水平' },
    { code: 'B4.4', name: '与系统协同减排能力', l1: 'B4', desc: '与整车或系统协同实现减排' },
    { code: 'B4.5', name: '使用阶段数据支持能力', l1: 'B4', desc: '使用阶段性能与能耗数据获取能力' },
    { code: 'B5.1', name: '产品可回收率', l1: 'B5', desc: '产品及材料的可回收比例' },
    { code: 'B5.2', name: '可再制造与再利用', l1: 'B5', desc: '再制造、再利用设计与实践' },
    { code: 'B5.3', name: '回收责任与机制', l1: 'B5', desc: '回收责任落实及机制建设' },
    { code: 'B5.4', name: '回收数据与闭环管理', l1: 'B5', desc: '回收数据采集与闭环管理能力' },
    { code: 'B5.5', name: '符合法规与延伸责任', l1: 'B5', desc: '符合 EPR、电池等相关法规' },
    { code: 'C1.1', name: '供应商碳排放识别', l1: 'C1', desc: '是否识别关键供应商及其排放类型' },
    { code: 'C1.2', name: '供应商碳数据获取', l1: 'C1', desc: '获取供应商碳数据的机制与覆盖' },
    { code: 'C1.3', name: '供应商碳信息披露', l1: 'C1', desc: '供应商碳信息披露的完整性与频率' },
    { code: 'C1.4', name: '供应商碳数据质量', l1: 'C1', desc: '供应商数据的准确性、可核查性' },
    { code: 'C1.5', name: '供应商碳核算规范性', l1: 'C1', desc: '供应商核算方法与口径一致性' },
    { code: 'C1.6', name: '供应商第三方核查', l1: 'C1', desc: '供应商是否接受第三方核查' },
    { code: 'C2.1', name: '关键原材料识别', l1: 'C2', desc: '钢、铝、电池材料等关键材料识别' },
    { code: 'C2.2', name: '原材料碳强度水平', l1: 'C2', desc: '关键材料单位排放水平' },
    { code: 'C2.3', name: '原材料来源结构', l1: 'C2', desc: '不同来源（地区/工艺）的构成' },
    { code: 'C2.4', name: '高碳材料替代能力', l1: 'C2', desc: '对高碳材料的替代方案与可行性' },
    { code: 'C2.5', name: '原材料碳风险暴露', l1: 'C2', desc: '对 CBAM、价格等风险的暴露程度' },
    { code: 'C3.1', name: '联合减排机制', l1: 'C3', desc: '是否建立供应链联合减排机制' },
    { code: 'C3.2', name: '技术与管理赋能', l1: 'C3', desc: '为供应商提供技术或管理支持' },
    { code: 'C3.3', name: '减排项目协同实施', l1: 'C3', desc: '供应链减排项目的实施情况' },
    { code: 'C3.4', name: '协同减排绩效评估', l1: 'C3', desc: '对协同减排效果的评估' },
    { code: 'C3.5', name: '激励与约束机制', l1: 'C3', desc: '激励与约束并存的管理机制' },
    { code: 'C4.1', name: '运输方式结构', l1: 'C4', desc: '不同运输方式（公路/铁路/水运）' },
    { code: 'C4.2', name: '运输路径与效率', l1: 'C4', desc: '路径优化、装载率与效率' },
    { code: 'C4.3', name: '低碳运输工具应用', l1: 'C4', desc: '新能源车辆、低碳船舶等' },
    { code: 'C4.4', name: '物流碳排放核算', l1: 'C4', desc: '物流环节碳排放核算能力' },
    { code: 'C4.5', name: '物流协同与共享', l1: 'C4', desc: '物流资源共享与协同管理' },
    { code: 'C5.1', name: '政策与合规风险识别', l1: 'C5', desc: '对政策与法规变化的识别能力' },
    { code: 'C5.2', name: '碳成本与价格风险', l1: 'C5', desc: '对碳成本波动的应对能力' },
    { code: 'C5.3', name: '供应中断与替代能力', l1: 'C5', desc: '关键供应中断的应急与替代' },
    { code: 'C5.4', name: '多元化与本地化布局', l1: 'C5', desc: '供应来源多元化、本地化水平' },
    { code: 'C5.5', name: '供应链风险评估机制', l1: 'C5', desc: '系统化风险评估与预警机制' },
    { code: 'D1.1', name: '双碳政策目标适应性', l1: 'D1', desc: '企业碳减排目标与国家双碳战略目标的一致性' },
    { code: 'D1.2', name: '碳排放配额管理', l1: 'D1', desc: '是否参与排放交易体系并管理碳配额' },
    { code: 'D1.3', name: '排放法规遵循情况', l1: 'D1', desc: '符合国家或地方排放法规的合规性' },
    { code: 'D1.4', name: '行业标准符合性', l1: 'D1', desc: '是否符合行业内关于低碳、环保的技术标准和规范' },
    { code: 'D1.5', name: '绿色供应链管理', l1: 'D1', desc: '是否建立绿色供应链管理体系，落实绿色采购政策' },
    { code: 'D2.1', name: 'CBAM政策适应性', l1: 'D2', desc: '对碳边境调整机制（CBAM）要求的合规性评估' },
    { code: 'D2.2', name: '出口产品碳披露', l1: 'D2', desc: '出口产品碳足迹的披露与报告情况' },
    { code: 'D2.3', name: '国际市场碳合规风险', l1: 'D2', desc: '对国际市场的碳合规性风险评估' },
    { code: 'D2.4', name: '碳排放标签与认证', l1: 'D2', desc: '产品是否获得国际碳排放标签或认证' },
    { code: 'D2.5', name: '国际合规标准对接', l1: 'D2', desc: '符合欧盟、美国等主要经济体的碳排放和环保标准' },
    { code: 'D3.1', name: 'ISO 14001 环境管理认证', l1: 'D3', desc: '是否持有 ISO 14001 环境管理体系认证' },
    { code: 'D3.2', name: '碳足迹认证', l1: 'D3', desc: '产品或企业是否获得碳足迹认证' },
    { code: 'D3.3', name: '第三方碳核查', l1: 'D3', desc: '是否接受第三方机构的碳排放核查与审核' },
    { code: 'D3.4', name: '碳减排项目认证', l1: 'D3', desc: '是否参与经认证的碳减排项目' },
    { code: 'D3.5', name: 'ESG 报告与认证', l1: 'D3', desc: '是否披露符合国际标准的 ESG 报告' },
    { code: 'D4.1', name: '碳排放数据透明度', l1: 'D4', desc: '碳排放数据的公开透明度，是否按期披露' },
    { code: 'D4.2', name: 'ESG 报告质量', l1: 'D4', desc: 'ESG报告的质量与全面性' },
    { code: 'D4.3', name: '供应链碳数据披露', l1: 'D4', desc: '是否与关键供应商共享碳排放数据并进行披露' },
    { code: 'D4.4', name: '数据审计与验证', l1: 'D4', desc: '是否对披露的碳数据进行审计和第三方验证' },
    { code: 'D4.5', name: '碳风险报告与应对', l1: 'D4', desc: '是否定期发布碳风险评估报告' },
    { code: 'E1.1', name: '数据采集系统覆盖范围', l1: 'E1', desc: '是否具备覆盖全生产、运营环节的碳与能源数据采集系统' },
    { code: 'E1.2', name: '实时数据采集能力', l1: 'E1', desc: '碳、能源数据的实时采集能力' },
    { code: 'E1.3', name: '数据采集精度与准确性', l1: 'E1', desc: '数据采集设备精度与采集方法的准确性' },
    { code: 'E1.4', name: '数据自动化采集', l1: 'E1', desc: '是否通过自动化手段收集数据' },
    { code: 'E1.5', name: '数据采集频率', l1: 'E1', desc: '数据采集的频率与间隔' },
    { code: 'E2.1', name: '数据完整性', l1: 'E2', desc: '数据采集是否覆盖所有关键环节' },
    { code: 'E2.2', name: '数据一致性', l1: 'E2', desc: '数据之间是否一致' },
    { code: 'E2.3', name: '数据准确性', l1: 'E2', desc: '数据是否经过校验' },
    { code: 'E2.4', name: '数据时间戳与历史记录', l1: 'E2', desc: '数据是否具备时间戳' },
    { code: 'E2.5', name: '数据来源标识与验证', l1: 'E2', desc: '数据来源是否清晰' },
    { code: 'E3.1', name: '碳与能源管理信息系统', l1: 'E3', desc: '是否建立完善的碳与能源管理信息系统' },
    { code: 'E3.2', name: '自动化核算与报告功能', l1: 'E3', desc: '是否具备自动化计算碳排放与能源消耗并生成报告的能力' },
    { code: 'E3.3', name: '数据接口与集成能力', l1: 'E3', desc: '能否与其他系统无缝集成' },
    { code: 'E3.4', name: '数据分析与挖掘功能', l1: 'E3', desc: '系统是否具备实时数据分析、趋势预测等功能' },
    { code: 'E3.5', name: '数据可视化展示能力', l1: 'E3', desc: '是否支持数据可视化工具' },
    { code: 'E4.1', name: '数据隐私保护与合规', l1: 'E4', desc: '数据是否符合隐私保护法规' },
    { code: 'E4.2', name: '数据安全性与防护措施', l1: 'E4', desc: '数据是否受到严格的安全保护' },
    { code: 'E4.3', name: '数据存储与备份管理', l1: 'E4', desc: '数据存储是否符合合规要求' },
    { code: 'E4.4', name: '数据访问控制与权限管理', l1: 'E4', desc: '是否通过严格的访问控制确保数据安全' },
    { code: 'E4.5', name: '数据审计与监控', l1: 'E4', desc: '是否具备数据使用和访问的审计机制' },
    { code: 'F1.1', name: '低碳技术研发投入', l1: 'F1', desc: '是否在低碳技术上投入研发' },
    { code: 'F1.2', name: '技术转化与应用', l1: 'F1', desc: '是否将研发的低碳技术成功转化并应用到生产中' },
    { code: 'F1.3', name: '工艺创新与低碳化', l1: 'F1', desc: '是否采用创新的生产工艺' },
    { code: 'F1.4', name: '清洁能源与绿色制造技术', l1: 'F1', desc: '是否引入清洁能源和绿色制造技术' },
    { code: 'F1.5', name: '可持续技术与未来发展', l1: 'F1', desc: '是否持续开发与未来低碳发展的相关技术' },
    { code: 'F2.1', name: '新能源车技术发展', l1: 'F2', desc: '是否加大对新能源汽车的研发与投资' },
    { code: 'F2.2', name: '电池技术与储能解决方案', l1: 'F2', desc: '是否投入电池技术的研发与应用' },
    { code: 'F2.3', name: '替代材料与低碳设计', l1: 'F2', desc: '是否采用低碳替代材料或工艺设计' },
    { code: 'F2.4', name: '绿色物流与运输替代方案', l1: 'F2', desc: '是否探索低碳的物流和运输解决方案' },
    { code: 'F2.5', name: '清洁能源应用布局', l1: 'F2', desc: '是否发展和部署清洁能源技术' },
    { code: 'F3.1', name: '中长期碳减排目标', l1: 'F3', desc: '是否设立中长期的碳减排目标' },
    { code: 'F3.2', name: '碳中和路线图与时间表', l1: 'F3', desc: '是否制定碳中和的路线图和实施时间表' },
    { code: 'F3.3', name: '投资与资源配置', l1: 'F3', desc: '是否根据碳减排目标配置必要的资金与资源' },
    { code: 'F3.4', name: '碳风险与机会管理', l1: 'F3', desc: '是否识别碳排放的相关风险与机遇' },
    { code: 'F3.5', name: '碳政策适应与前瞻性思维', l1: 'F3', desc: '是否根据碳政策变化动态调整碳战略' },
    { code: 'F4.1', name: '绿色融资支持能力', l1: 'F4', desc: '是否获取绿色债券、绿色基金等融资渠道' },
    { code: 'F4.2', name: '绿色项目投资比例', l1: 'F4', desc: '是否增加绿色、低碳项目的投资比例' },
    { code: 'F4.3', name: '内部激励与碳绩效挂钩', l1: 'F4', desc: '是否建立低碳绩效激励机制' },
    { code: 'F4.4', name: '投资回报分析与评估', l1: 'F4', desc: '对绿色低碳项目的投资回报进行评估' },
    { code: 'F4.5', name: '外部绿色合作与联盟', l1: 'F4', desc: '是否与外部机构形成低碳合作伙伴关系' },
    { code: 'G1.1', name: '行业低碳标准倡导', l1: 'G1', desc: '是否积极参与行业低碳标准的制定与修订' },
    { code: 'G1.2', name: '行业减排目标制定', l1: 'G1', desc: '是否在行业层面设立并推动减排目标' },
    { code: 'G1.3', name: '公共政策支持与参与', l1: 'G1', desc: '是否参与政府或行业碳排放政策的讨论' },
    { code: 'G1.4', name: '行业内低碳技术推广', l1: 'G1', desc: '是否向同行推广低碳技术、管理经验' },
    { code: 'G1.5', name: '行业低碳合作联盟', l1: 'G1', desc: '是否加入低碳、绿色发展相关的行业联盟' },
    { code: 'G2.1', name: '员工绿色技能培训', l1: 'G2', desc: '是否为员工提供低碳相关技能的培训' },
    { code: 'G2.2', name: '公平就业与多样性', l1: 'G2', desc: '是否积极推动多元化与包容性' },
    { code: 'G2.3', name: '员工健康与福利', l1: 'G2', desc: '是否为员工提供健康保障及低碳工作环境' },
    { code: 'G2.4', name: '安全生产与风险防控', l1: 'G2', desc: '是否建立完善的安全生产体系' },
    { code: 'G2.5', name: '工会与员工参与机制', l1: 'G2', desc: '是否设立员工代表机制' },
    { code: 'G3.1', name: '社会公益投资', l1: 'G3', desc: '是否有专门的绿色公益项目' },
    { code: 'G3.2', name: '绿色教育与社会科普', l1: 'G3', desc: '是否开展绿色教育、低碳生活方式的社会科普' },
    { code: 'G3.3', name: '本地社区发展支持', l1: 'G3', desc: '是否支持本地社区的绿色发展' },
    { code: 'G3.4', name: '自然保护与生态贡献', l1: 'G3', desc: '是否参与植树造林、生态保护等' },
    { code: 'G3.5', name: '应急响应与灾后恢复', l1: 'G3', desc: '在自然灾害中是否提供资源支持' },
    { code: 'G4.1', name: '绿色产品推广', l1: 'G4', desc: '是否将低碳、环保产品推广至社会' },
    { code: 'G4.2', name: '环境影响评估与治理', l1: 'G4', desc: '是否进行环境影响评估' },
    { code: 'G4.3', name: '绿色创新带动', l1: 'G4', desc: '是否在社会层面促进绿色创新' },
    { code: 'G4.4', name: '资源共享与循环经济', l1: 'G4', desc: '是否支持资源共享和循环经济模式' },
    { code: 'G4.5', name: '碳排放公共披露', l1: 'G4', desc: '是否公开披露碳排放、能耗等环境数据' },
    { code: 'H1.1', name: '绿色消费需求预测', l1: 'H1', desc: '是否对绿色消费市场趋势进行预测' },
    { code: 'H1.2', name: '绿色产品市场份额', l1: 'H1', desc: '企业绿色低碳产品在市场中的份额' },
    { code: 'H1.3', name: '客户绿色需求识别', l1: 'H1', desc: '是否能够识别并响应客户绿色需求' },
    { code: 'H1.4', name: '绿色消费行为调研', l1: 'H1', desc: '是否开展绿色消费趋势调研' },
    { code: 'H1.5', name: '市场竞争力评估', l1: 'H1', desc: '在绿色低碳领域的市场竞争力' },
    { code: 'H2.1', name: '绿色品牌认知度', l1: 'H2', desc: '消费者对企业绿色品牌的认知度' },
    { code: 'H2.2', name: '绿色产品口碑与评价', l1: 'H2', desc: '客户对绿色低碳产品的反馈' },
    { code: 'H2.3', name: '产品绿色价值传递', l1: 'H2', desc: '企业是否能有效传递产品的绿色价值' },
    { code: 'H2.4', name: '客户绿色教育与引导', l1: 'H2', desc: '企业是否为客户提供绿色消费教育' },
    { code: 'H2.5', name: '客户满意度与忠诚度', l1: 'H2', desc: '客户对绿色产品的满意度与忠诚度' },
    { code: 'H3.1', name: '绿色产品营销策略', l1: 'H3', desc: '是否有专门的绿色产品营销策略' },
    { code: 'H3.2', name: '绿色产品推广渠道', l1: 'H3', desc: '推广渠道是否多元化' },
    { code: 'H3.3', name: '环保认证与标签应用', l1: 'H3', desc: '是否通过环保认证提升竞争力' },
    { code: 'H3.4', name: '市场教育与推广活动', l1: 'H3', desc: '是否组织绿色低碳市场推广活动' },
    { code: 'H3.5', name: '合作伙伴与生态圈建设', l1: 'H3', desc: '是否与其他绿色企业建立合作' },
    { code: 'H4.1', name: '客户绿色合规要求', l1: 'H4', desc: '是否识别并响应客户绿色合规要求' },
    { code: 'H4.2', name: '客户绿色投诉与反馈处理', l1: 'H4', desc: '是否建立绿色产品投诉反馈机制' },
    { code: 'H4.3', name: '产品生命周期跟踪与支持', l1: 'H4', desc: '是否提供全生命周期跟踪' },
    { code: 'H4.4', name: '客户绿色责任信息披露', l1: 'H4', desc: '是否按要求披露产品绿色责任' },
    { code: 'H4.5', name: '定期客户绿色满意度调查', l1: 'H4', desc: '是否定期进行绿色满意度调查' },
];

// ===== 评估方案适用场景 (Assessment Scenarios) =====
const ASSESSMENT_SCENARIOS = [
    { id: 'Scene-A', name: '新供应商准入绿色能力审查', target: '一级供应商、二级供应商', applicable: '所有新引入的潜在供应商', value: '避免引入高碳、高风险供应商，建立绿色准入门槛，降低供应链起始碳足迹', priority: '高' },
    { id: 'Scene-B', name: '年度供应商绿色绩效考核', target: '所有在合作供应商', applicable: '所有合作中供应商（重点A、B级）', value: '将绿色维度纳入年度综合评分（权重10–25%），直接影响订单、账期、评优资格', priority: '高' },
    { id: 'Scene-C', name: '战略/核心供应商年度综合评估', target: '一级供应商（战略级）', applicable: 'A级战略供应商、采购额前10%、高排放供应商', value: '全面掌握战略供应商全链低碳能力，作为长期合作、联合研发、优先支持依据', priority: '高' },
    { id: 'Scene-D', name: '新车型/新平台开发供应商导入评估', target: '一级供应商', applicable: '参与新车型开发的所有一级供应商', value: '确保新车型从零部件设计阶段满足低碳目标，支持整车产品碳足迹达标', priority: '高' },
    { id: 'Scene-E', name: '关键材料绿色替代与选型评估', target: '关键原材料供应商、二级供应商', applicable: '钢材、铝材、塑料、电池材料供应商', value: '为低碳材料切换提供量化对比依据，推动高碳材料替代，降低产品碳强度', priority: '高' },
    { id: 'Scene-F', name: '动力电池全供应链碳足迹专项评估', target: '电池全链企业', applicable: '正极/负极/电芯/PACK/BMS 等全链供应商', value: '满足电池护照、双积分、碳足迹披露要求，支持整车电池碳足迹合规与降本', priority: '高' },
    { id: 'Scene-G', name: '出口欧盟/北美供应商 CBAM 合规评估', target: '涉及出口的供应商', applicable: '出口欧盟/北美、钢铝电池等CBAM品类供应商', value: '提前识别碳关税风险，提供碳价影响测算和应对方案，避免额外关税成本', priority: '高' },
    { id: 'Scene-H', name: '供应链上游减排协同项目筛选', target: '一级供应商 + 其二级供应商', applicable: '一级核心供应商 + 关键二级供应商', value: '精准挑选适合开展联合减排、技术攻关、资金支持的供应商组合，提高协同效率', priority: '高' },
    { id: 'Scene-I', name: '供应商绿色能力分级与梯队管理', target: '所有供应商', applicable: '所有供应商（分层后全覆盖）', value: '形成优秀-良好-一般-需改进四级梯队，实现差异化赋能、激励、约束与淘汰', priority: '中' },
    { id: 'Scene-J', name: '年度绿色供应链标杆供应商评选', target: '所有供应商', applicable: '绿色表现优秀供应商', value: '选出年度绿色标杆，在供应商大会表彰、分享经验，带动全链改进氛围', priority: '中' },
    { id: 'Scene-K', name: '整改跟踪评估', target: '上一轮评级较低的供应商', applicable: '上一轮评级为一般或需改进的供应商', value: '验证整改措施执行效果，判断是否退出整改名单，避免风险长期累积', priority: '高' },
    { id: 'Scene-L', name: '关键原材料低碳风险与替代路径评估', target: '关键原材料供应商', applicable: '钢厂、铝厂、锂盐、正极/负极材料供应商', value: '识别高碳原材料供应链风险，提前布局低碳替代来源，降低未来碳成本冲击', priority: '高' },
    { id: 'Scene-M', name: '物流运输与仓储低碳化专项评估', target: '物流服务商', applicable: '干线/支线物流、仓储、国际货代企业', value: '推动物流环节电动化/新能源化，降低供应链中运输碳排放占比', priority: '中' },
    { id: 'Scene-N', name: '供应商 ESG/绿色报告披露能力评估', target: '一级供应商 + 部分二级供应商', applicable: '所有一级供应商 + 重要二级供应商', value: '评估供应商 ESG 报告质量与披露意愿，支持整车厂 Scope 3 数据填报合规', priority: '中' },
    { id: 'Scene-O', name: '绿色供应链示范项目/联合减碳试点遴选', target: '绿色表现优秀供应商', applicable: '绿色表现优秀、配合度高的供应商（通常 A 级）', value: '筛选最适合开展联合减碳、技术示范、绿色金融支持的合作伙伴，树立行业标杆', priority: '中' },
];

// ===== 评分规则模板 =====
const SCORING_RULES = [
    { id: 'RULE-LINEAR', name: '线性比例评分', desc: '得分 = (实际值/基准值) × 满分，封顶10分', formula: 'score = min(actual/benchmark * 10, 10)' },
    { id: 'RULE-THRESHOLD', name: '阈值等级评分', desc: '按阈值区间评分：优秀(10)、合格(7)、待改进(4)、不合格(0)', formula: '≥90%→10, 70-89%→7, 60-69%→4, <60%→0' },
    { id: 'RULE-BINARY', name: '是否达标评分', desc: '达标得满分10，未达标得0分', formula: 'yes→10, no→0' },
    { id: 'RULE-WEIGHTED', name: '加权综合评分', desc: '各子项得分按权重汇总', formula: 'Σ(score_i × weight_i)' },
    { id: 'RULE-INVERSE', name: '反向指标评分', desc: '指标值越低越好，如碳排放强度、敏感度', formula: 'score = max(0, 10 - (actual/benchmark) * 10)' },
];

// ===== 评估方案 (Assessment Plans) =====
const ASSESSMENT_PLANS = [
    {
        id: 'PLAN-001', name: '2026年度供应商绿色绩效综合评估', scenario: 'Scene-B',
        status: '进行中', startDate: '2026-01-15', endDate: '2026-03-31', responsible: '张主管',
        targetCount: 12, completedCount: 3,
        purpose: '将绿色低碳维度纳入年度供应商综合考核，权重占比15%，评估结果直接影响订单分配、账期及评优资格，推动供应链绿色转型',
        scoringRule: 'RULE-LINEAR',
        gradeThresholds: { excellent: 90, good: 70, fair: 60 },
        categories: ['A','B','C','D'],
        categoryWeights: { A: 30, B: 25, C: 25, D: 20 },
        targetSuppliers: ['S001','S002','S003','S004','S005','S006','S007','S008','S009','S010','S011','S012'],
        selectedL1: ['A1','A2','A3','B1','B2','B3','C1','C2','C3','D1','D2','D3'],
    },
    {
        id: 'PLAN-002', name: '新车型平台供应商导入绿色评估', scenario: 'Scene-D',
        status: '计划中', startDate: '2026-03-01', endDate: '2026-05-30', responsible: '李经理',
        targetCount: 8, completedCount: 0,
        purpose: '确保参与新车型EP32平台开发的零部件供应商从设计源头满足低碳目标，支持整车产品碳足迹LCA达标及欧盟碳披露合规',
        scoringRule: 'RULE-THRESHOLD',
        gradeThresholds: { excellent: 85, good: 70, fair: 55 },
        categories: ['A','B','C'],
        categoryWeights: { A: 25, B: 40, C: 35 },
        targetSuppliers: ['S001','S003','S004','S006','S008'],
        selectedL1: ['A1','A2','B1','B2','B3','B4','B5','C1','C2','C4'],
    },
    {
        id: 'PLAN-003', name: '出口供应商 CBAM 合规专项评估', scenario: 'Scene-G',
        status: '已完成', startDate: '2025-10-01', endDate: '2025-12-31', responsible: '王主管',
        targetCount: 5, completedCount: 5,
        purpose: '提前识别出口欧盟/北美的供应商碳关税风险，对钢铝电池等CBAM品类供应商开展碳成本影响测算，制定合规应对方案',
        scoringRule: 'RULE-WEIGHTED',
        gradeThresholds: { excellent: 90, good: 75, fair: 60 },
        categories: ['A','C','D'],
        categoryWeights: { A: 30, C: 30, D: 40 },
        targetSuppliers: ['S001','S009','S010','S011','S012'],
        selectedL1: ['A1','A3','C2','C5','D1','D2','D3','D4'],
    },
    {
        id: 'PLAN-004', name: '战略供应商年度综合评估（S001）', scenario: 'Scene-C',
        status: '已完成', startDate: '2025-11-01', endDate: '2026-01-15', responsible: '张主管',
        targetCount: 1, completedCount: 1,
        purpose: '对A级战略供应商S001全面评估全链低碳能力，涵盖所有8个维度，作为长期合作、联合研发及优先支持决策依据',
        scoringRule: 'RULE-LINEAR',
        gradeThresholds: { excellent: 90, good: 70, fair: 60 },
        categories: ['A','B','C','D','E','F','G','H'],
        categoryWeights: { A: 20, B: 15, C: 20, D: 10, E: 10, F: 10, G: 8, H: 7 },
        targetSuppliers: ['S001'],
        selectedL1: ['A1','A2','A3','A4','A5','B1','B2','B3','B4','B5','C1','C2','C3','C4','C5','D1','D2','D3','D4','E1','E2','E3','E4','F1','F2','F3','F4','G1','G2','G3','G4','H1','H2','H3','H4'],
    },
    {
        id: 'PLAN-005', name: '关键材料低碳替代评估', scenario: 'Scene-E',
        status: '进行中', startDate: '2026-02-01', endDate: '2026-04-30', responsible: '赵工',
        targetCount: 6, completedCount: 2,
        purpose: '为钢材、铝材、锂盐等关键高碳材料的低碳替代提供量化对比依据，推动产品碳强度下降，降低CBAM成本风险',
        scoringRule: 'RULE-LINEAR',
        gradeThresholds: { excellent: 85, good: 70, fair: 55 },
        categories: ['B','C'],
        categoryWeights: { B: 55, C: 45 },
        targetSuppliers: ['S009','S010','S012','S003','S005','S006'],
        selectedL1: ['B1','B3','B5','C1','C2','C3'],
    },
    {
        id: 'PLAN-006', name: '动力电池供应链碳足迹专项评估', scenario: 'Scene-F',
        status: '计划中', startDate: '2026-04-01', endDate: '2026-06-30', responsible: '陈经理',
        targetCount: 10, completedCount: 0,
        purpose: '满足欧盟电池护照、双积分、碳足迹披露要求，对电池全链（正极/负极/电芯/PACK/BMS）供应商实施碳足迹专项评估',
        scoringRule: 'RULE-WEIGHTED',
        gradeThresholds: { excellent: 88, good: 72, fair: 58 },
        categories: ['A','B','C','D','E'],
        categoryWeights: { A: 20, B: 30, C: 20, D: 15, E: 15 },
        targetSuppliers: ['S001','S003','S004','S005','S008','S009','S010'],
        selectedL1: ['A1','A2','A4','B1','B2','B3','B4','B5','C1','C2','C4','D1','D2','D3','E1','E2'],
    },
];

// ===== 供应商 (Suppliers) =====
const SUPPLIERS = [
    { id: 'S001', name: '上海鑫能汽车零部件有限公司', industry: '汽车零部件制造', level: '一级供应商', status: '合作中', contact: '张伟', phone: '021-88881234', grade: 'A', region: '华东', hasData: true },
    { id: 'S002', name: '苏州博锐精密模具有限公司', industry: '精密模具制造', level: '二级供应商', status: '合作中', contact: '李明', phone: '0512-65553456', grade: 'B', region: '华东', hasData: false },
    { id: 'S003', name: '宁波华翔新材料科技有限公司', industry: '新材料研发', level: '一级供应商', status: '合作中', contact: '王芳', phone: '0574-87776543', grade: 'A', region: '华东', hasData: false },
    { id: 'S004', name: '广州力合动力系统有限公司', industry: '动力系统总成', level: '一级供应商', status: '合作中', contact: '陈强', phone: '020-23456789', grade: 'B', region: '华南', hasData: false },
    { id: 'S005', name: '天津中科新能源科技有限公司', industry: '新能源电池', level: '一级供应商', status: '合作中', contact: '刘洋', phone: '022-37891234', grade: 'C', region: '华北', hasData: false },
    { id: 'S006', name: '武汉瑞通底盘零部件有限公司', industry: '底盘零部件', level: '二级供应商', status: '合作中', contact: '赵刚', phone: '027-65551111', grade: 'B', region: '华中', hasData: false },
    { id: 'S007', name: '重庆鼎盛传动科技有限公司', industry: '传动系统', level: '一级供应商', status: '暂停合作', contact: '孙丽', phone: '023-86667890', grade: 'D', region: '西南', hasData: false },
    { id: 'S008', name: '长春一汽富维电子有限公司', industry: '汽车电子', level: '二级供应商', status: '合作中', contact: '周涛', phone: '0431-89012345', grade: 'B', region: '东北', hasData: false },
    { id: 'S009', name: '深圳绿能新材料有限公司', industry: '锂电正极材料', level: '关键原材料供应商', status: '合作中', contact: '吴静', phone: '0755-82345678', grade: 'A', region: '华南', hasData: false },
    { id: 'S010', name: '河北冀南钢铁集团有限公司', industry: '钢铁冶炼', level: '关键原材料供应商', status: '合作中', contact: '郑凯', phone: '0310-23456789', grade: 'C', region: '华北', hasData: false },
    { id: 'S011', name: '中通快运物流有限公司', industry: '物流运输', level: '物流服务商', status: '合作中', contact: '马晓', phone: '0537-34567890', grade: 'B', region: '华东', hasData: false },
    { id: 'S012', name: '包头中润铝业有限公司', industry: '铝材加工', level: '关键原材料供应商', status: '合作中', contact: '黄磊', phone: '0472-45678901', grade: 'C', region: '华北', hasData: false },
];

// ===== 供应商 S001 三级指标评估数据 =====
const S001_SCORES = [
    // A1 温室气体排放与核算能力
    { l3code: 'A1.1.1', name: '排放源识别覆盖率', l2: 'A1.1', l1: 'A1', type: 'A', actual: 92, benchmark: 100, score: 9.2 },
    { l3code: 'A1.1.2', name: '边界界定文档完整度', l2: 'A1.1', l1: 'A1', type: 'A', actual: 4.5, benchmark: 5, score: 9.0 },
    { l3code: 'A1.1.3', name: '边界定义年度审查频率', l2: 'A1.1', l1: 'A1', type: 'A', actual: 3, benchmark: 4, score: 7.5 },
    { l3code: 'A1.2.1', name: '直接排放源计量覆盖率', l2: 'A1.2', l1: 'A1', type: 'A', actual: 88, benchmark: 100, score: 8.8 },
    { l3code: 'A1.2.2', name: 'Scope 1 数据采集准确率', l2: 'A1.2', l1: 'A1', type: 'A', actual: 2, benchmark: 5, score: 6.0 },
    { l3code: 'A1.2.3', name: 'Scope 1 移动源排放追踪率', l2: 'A1.2', l1: 'A1', type: 'A', actual: 85, benchmark: 100, score: 8.5 },
    { l3code: 'A1.3.1', name: '电力/热力计量覆盖率', l2: 'A1.3', l1: 'A1', type: 'A', actual: 95, benchmark: 100, score: 9.5 },
    { l3code: 'A1.3.2', name: '排放因子更新及时性', l2: 'A1.3', l1: 'A1', type: 'A', actual: 3.5, benchmark: 4, score: 8.75 },
    { l3code: 'A1.4.1', name: 'Scope 3 类别覆盖数量', l2: 'A1.4', l1: 'A1', type: 'A', actual: 13, benchmark: 15, score: 8.67 },
    { l3code: 'A1.4.2', name: 'Scope 3 上游数据获取覆盖率', l2: 'A1.4', l1: 'A1', type: 'A', actual: 80, benchmark: 100, score: 8.0 },
    { l3code: 'A1.4.3', name: 'Scope 3 使用阶段估算准确度', l2: 'A1.4', l1: 'A1', type: 'A', actual: 7, benchmark: 10, score: 3.0 },
    { l3code: 'A1.5.1', name: '核算方法与标准一致性', l2: 'A1.5', l1: 'A1', type: 'A', actual: 90, benchmark: 100, score: 9.0 },
    { l3code: 'A1.6.1', name: '碳排放数据内部审计频率', l2: 'A1.6', l1: 'A1', type: 'A', actual: 3, benchmark: 4, score: 7.5 },
    { l3code: 'A1.6.2', name: '碳排放数据第三方核查覆盖率', l2: 'A1.6', l1: 'A1', type: 'A', actual: 75, benchmark: 100, score: 7.5 },
    // A2 能源结构与能源效率
    { l3code: 'A2.1.1', name: '清洁能源使用占比', l2: 'A2.1', l1: 'A2', type: 'A', actual: 35, benchmark: 30, score: 10 },
    { l3code: 'A2.1.2', name: '绿电采购或自发自用比例', l2: 'A2.1', l1: 'A2', type: 'A', actual: 40, benchmark: 30, score: 10 },
    { l3code: 'A2.2.1', name: '单位产品/产值能耗水平', l2: 'A2.2', l1: 'A2', type: 'A', actual: 85, benchmark: 100, score: 8.5 },
    { l3code: 'A2.2.2', name: '单位能耗年度下降率', l2: 'A2.2', l1: 'A2', type: 'A', actual: 6, benchmark: 5, score: 10 },
    { l3code: 'A2.3.1', name: '关键用能节点计量覆盖率', l2: 'A2.3', l1: 'A2', type: 'A', actual: 92, benchmark: 100, score: 9.2 },
    { l3code: 'A2.4.1', name: '能效对标行业基准偏差率', l2: 'A2.4', l1: 'A2', type: 'A', actual: 8, benchmark: 10, score: 2.0 },
    // A3 碳管理体系与治理能力
    { l3code: 'A3.1.1', name: '碳管理组织架构完整度', l2: 'A3.1', l1: 'A3', type: 'A', actual: 95, benchmark: 100, score: 9.5 },
    { l3code: 'A3.2.1', name: '碳管理制度与流程文件数量', l2: 'A3.2', l1: 'A3', type: 'A', actual: 6, benchmark: 5, score: 10 },
    { l3code: 'A3.4.1', name: '碳风险识别与评估覆盖度', l2: 'A3.4', l1: 'A3', type: 'A', actual: 85, benchmark: 100, score: 8.5 },
    // A4 减排绩效与持续改进
    { l3code: 'A4.1.1', name: '近三年碳排放总量下降率', l2: 'A4.1', l1: 'A4', type: 'A', actual: 12, benchmark: 15, score: 8.0 },
    // B1 产品碳足迹与LCA
    { l3code: 'B1.1.1', name: '已开展碳足迹核算的产品覆盖率', l2: 'B1.1', l1: 'B1', type: 'B', actual: 90, benchmark: 100, score: 9.0 },
    { l3code: 'B1.1.2', name: '产品碳足迹核算标准符合度', l2: 'B1.1', l1: 'B1', type: 'B', actual: 95, benchmark: 100, score: 9.5 },
    { l3code: 'B1.2.1', name: '生命周期边界定义完整度', l2: 'B1.2', l1: 'B1', type: 'B', actual: 88, benchmark: 100, score: 8.8 },
    { l3code: 'B1.3.1', name: 'LCA 阶段覆盖完整度', l2: 'B1.3', l1: 'B1', type: 'B', actual: 92, benchmark: 100, score: 9.2 },
    { l3code: 'B1.4.1', name: '一手数据在 LCA 中的占比', l2: 'B1.4', l1: 'B1', type: 'B', actual: 75, benchmark: 80, score: 9.375 },
    // B2 产品设计低碳性
    { l3code: 'B2.1.1', name: '产品重量轻量化比例', l2: 'B2.1', l1: 'B2', type: 'B', actual: 11, benchmark: 10, score: 10 },
    { l3code: 'B2.2.1', name: '模块化/平台化设计复用率', l2: 'B2.2', l1: 'B2', type: 'B', actual: 68, benchmark: 70, score: 9.71 },
    { l3code: 'B2.3.1', name: '设计阶段碳影响评估覆盖率', l2: 'B2.3', l1: 'B2', type: 'B', actual: 90, benchmark: 100, score: 9.0 },
    { l3code: 'B2.4.1', name: '产品可拆解性设计得分', l2: 'B2.4', l1: 'B2', type: 'B', actual: 85, benchmark: 100, score: 8.5 },
    // B3 材料与工艺低碳性
    { l3code: 'B3.1.1', name: '主要材料平均碳强度', l2: 'B3.1', l1: 'B3', type: 'B', actual: 85, benchmark: 100, score: 8.5 },
    { l3code: 'B3.2.1', name: '低碳/再生材料使用比例', l2: 'B3.2', l1: 'B3', type: 'B', actual: 22, benchmark: 20, score: 10 },
    { l3code: 'B3.3.1', name: '关键制造工艺碳排放强度', l2: 'B3.3', l1: 'B3', type: 'B', actual: 90, benchmark: 100, score: 9.0 },
    { l3code: 'B3.4.1', name: '低碳工艺改造项目数量', l2: 'B3.4', l1: 'B3', type: 'B', actual: 6, benchmark: 5, score: 10 },
    // B4 产品使用阶段减排贡献
    { l3code: 'B4.1.1', name: '对整车能效提升贡献率', l2: 'B4.1', l1: 'B4', type: 'B', actual: 6, benchmark: 5, score: 10 },
    { l3code: 'B4.2.1', name: '产品使用寿命设计指标', l2: 'B4.2', l1: 'B4', type: 'B', actual: 11, benchmark: 10, score: 10 },
    // B5 产品回收、再利用与末端管理
    { l3code: 'B5.1.1', name: '产品材料可回收率设计值', l2: 'B5.1', l1: 'B5', type: 'B', actual: 88, benchmark: 85, score: 10 },
    { l3code: 'B5.2.1', name: '关键部件再制造/再利用设计比例', l2: 'B5.2', l1: 'B5', type: 'B', actual: 55, benchmark: 50, score: 10 },
    { l3code: 'B5.3.1', name: '是否符合 EPR 要求', l2: 'B5.3', l1: 'B5', type: 'B', actual: '是', benchmark: '是', score: 10 },
    { l3code: 'B5.4.1', name: '回收闭环数据追踪能力', l2: 'B5.4', l1: 'B5', type: 'B', actual: '是', benchmark: '是', score: 10 },
    { l3code: 'B5.5.1', name: '回收责任机制落实率', l2: 'B5.5', l1: 'B5', type: 'B', actual: 95, benchmark: 100, score: 9.5 },
    // C1 上游供应商碳管理与披露
    { l3code: 'C1.1.1', name: '关键供应商识别率', l2: 'C1.1', l1: 'C1', type: 'C', actual: 95, benchmark: 100, score: 9.5 },
    { l3code: 'C1.2.1', name: '供应商碳排放数据获取覆盖率', l2: 'C1.2', l1: 'C1', type: 'C', actual: 88, benchmark: 100, score: 8.8 },
    { l3code: 'C1.2.2', name: '供应商碳数据报送频率', l2: 'C1.2', l1: 'C1', type: 'C', actual: 3.5, benchmark: 4, score: 8.75 },
    { l3code: 'C1.3.1', name: '供应商碳信息披露完整度', l2: 'C1.3', l1: 'C1', type: 'C', actual: 85, benchmark: 100, score: 8.5 },
    { l3code: 'C1.4.1', name: '供应商碳数据第三方核查比例', l2: 'C1.4', l1: 'C1', type: 'C', actual: 75, benchmark: 80, score: 9.375 },
    // C2 关键原材料低碳风险
    { l3code: 'C2.1.1', name: '关键高碳原材料种类识别数量', l2: 'C2.1', l1: 'C2', type: 'C', actual: 7, benchmark: 8, score: 8.75 },
    { l3code: 'C2.2.1', name: '关键原材料平均单位碳强度', l2: 'C2.2', l1: 'C2', type: 'C', actual: 90, benchmark: 100, score: 9.0 },
    { l3code: 'C2.3.1', name: '关键原材料低碳来源比例', l2: 'C2.3', l1: 'C2', type: 'C', actual: 45, benchmark: 50, score: 9.0 },
    { l3code: 'C2.4.1', name: '高碳材料替代方案数量', l2: 'C2.4', l1: 'C2', type: 'C', actual: 4, benchmark: 5, score: 8.0 },
    { l3code: 'C2.5.1', name: '关键原材料受CBAM影响比例', l2: 'C2.5', l1: 'C2', type: 'C', actual: 15, benchmark: 20, score: 2.5 },
    // C3 供应链减排协同与赋能
    { l3code: 'C3.1.1', name: '与供应商建立联合减排机制比例', l2: 'C3.1', l1: 'C3', type: 'C', actual: 75, benchmark: 80, score: 9.375 },
    { l3code: 'C3.2.1', name: '低碳技术赋能项目数量', l2: 'C3.2', l1: 'C3', type: 'C', actual: 4.5, benchmark: 5, score: 9.0 },
    { l3code: 'C3.3.1', name: '协同减排项目数量', l2: 'C3.3', l1: 'C3', type: 'C', actual: 4, benchmark: 5, score: 8.0 },
    { l3code: 'C3.3.2', name: '协同减排项目累计减排量', l2: 'C3.3', l1: 'C3', type: 'C', actual: 4500, benchmark: 5000, score: 9.0 },
    { l3code: 'C3.4.1', name: '协同减排绩效评估频率', l2: 'C3.4', l1: 'C3', type: 'C', actual: 1.5, benchmark: 2, score: 7.5 },
    { l3code: 'C3.5.1', name: '正向激励覆盖率', l2: 'C3.5', l1: 'C3', type: 'C', actual: 55, benchmark: 60, score: 9.167 },
    // C4 物流与运输低碳化
    { l3code: 'C4.1.1', name: '低碳运输方式占比', l2: 'C4.1', l1: 'C4', type: 'C', actual: 55, benchmark: 60, score: 9.167 },
    { l3code: 'C4.2.1', name: '运输平均装载率', l2: 'C4.2', l1: 'C4', type: 'C', actual: 80, benchmark: 85, score: 9.412 },
    { l3code: 'C4.3.1', name: '新能源运输工具使用比例', l2: 'C4.3', l1: 'C4', type: 'C', actual: 35, benchmark: 40, score: 8.75 },
    { l3code: 'C4.4.1', name: '物流碳排放核算覆盖率', l2: 'C4.4', l1: 'C4', type: 'C', actual: 95, benchmark: 100, score: 9.5 },
    // C5 供应链韧性与碳风险管理
    { l3code: 'C5.1.1', name: '碳政策风险识别类别数', l2: 'C5.1', l1: 'C5', type: 'C', actual: 7, benchmark: 8, score: 8.75 },
    { l3code: 'C5.2.1', name: '碳价波动对采购成本影响敏感度', l2: 'C5.2', l1: 'C5', type: 'C', actual: 4, benchmark: 5, score: 2.0 },
    { l3code: 'C5.3.1', name: '供应中断风险评估覆盖率', l2: 'C5.3', l1: 'C5', type: 'C', actual: 95, benchmark: 100, score: 9.5 },
    { l3code: 'C5.4.1', name: '供应来源多元化指数', l2: 'C5.4', l1: 'C5', type: 'C', actual: 4.5, benchmark: 5, score: 9.0 },
    { l3code: 'C5.5.1', name: '碳风险预警机制完善度', l2: 'C5.5', l1: 'C5', type: 'C', actual: 90, benchmark: 100, score: 9.0 },
    { l3code: 'C5.5.2', name: '碳风险应急预案演练频率', l2: 'C5.5', l1: 'C5', type: 'C', actual: 1.5, benchmark: 2, score: 7.5 },
];

// ===== Helper: compute aggregated scores for S001 =====
function computeS001Summary() {
    const byType = {};
    const byL1 = {};
    const byL2 = {};

    S001_SCORES.forEach(s => {
        if (!byType[s.type]) byType[s.type] = [];
        byType[s.type].push(s.score);

        if (!byL1[s.l1]) byL1[s.l1] = [];
        byL1[s.l1].push(s.score);

        if (!byL2[s.l2]) byL2[s.l2] = [];
        byL2[s.l2].push(s.score);
    });

    const avg = arr => arr.length ? +(arr.reduce((a, b) => a + b, 0) / arr.length).toFixed(2) : 0;

    return {
        byType: Object.fromEntries(Object.entries(byType).map(([k, v]) => [k, avg(v)])),
        byL1: Object.fromEntries(Object.entries(byL1).map(([k, v]) => [k, avg(v)])),
        byL2: Object.fromEntries(Object.entries(byL2).map(([k, v]) => [k, avg(v)])),
        overall: avg(S001_SCORES.map(s => s.score)),
    };
}
